Added --label

diff --git a/scripts/bbregister b/scripts/bbregister
--- a/scripts/bbregister
+++ b/scripts/bbregister
@@ -6,8 +6,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: greve $
-#    $Date: 2010/12/09 21:07:51 $
-#    $Revision: 1.35.2.5 $
+#    $Date: 2011/01/25 16:20:40 $
+#    $Revision: 1.35.2.6 $
 #
 # Copyright (C) 2002-2010,
 # The General Hospital Corporation (Boston, MA).
@@ -22,7 +22,7 @@
 #
 
 #
-set VERSION = '$Id: bbregister,v 1.35.2.5 2010/12/09 21:07:51 greve Exp $';
+set VERSION = '$Id: bbregister,v 1.35.2.6 2011/01/25 16:20:40 greve Exp $';
 set inputargs = ($argv);
 
 set subject = ();
@@ -75,6 +75,7 @@ set fsvol  = brainmask;
 set surfcost = ();
 set surfcon  = ();
 set surfname = "white";
+set MaskLabel = ();
 
 set RandInitMax = ();
 
@@ -193,6 +194,7 @@ if($DoPass1) then
   if($#GMProjAbs)  set cmd = ($cmd --gm-proj-abs  $GMProjAbs)
   if("$Contrast" == "-1") set cmd = ($cmd --wm-gt-gm $Slope1);
   if("$Contrast" == "+1") set cmd = ($cmd --gm-gt-wm $Slope1);
+  if($#MaskLabel)  set cmd = ($cmd --label $MaskLabel);
   if($LHOnly) set cmd = ($cmd --lh-only);
   if($RHOnly) set cmd = ($cmd --rh-only);
   if($UseEPIMask) set cmd = ($cmd --mask);
@@ -227,6 +229,7 @@ if($UseEPIMask) set cmd = ($cmd --mask);
 if(! $UseCortexLabel) set cmd = ($cmd --no-cortex-label);
 if($#VSM) set cmd = ($cmd --mask --vsm $VSM);
 if($#OutVol) set cmd = ($cmd --o $OutVol);
+if($#MaskLabel)  set cmd = ($cmd --label $MaskLabel);
 if("$Contrast" == "-1") set cmd = ($cmd --wm-gt-gm $Slope2);
 if("$Contrast" == "+1") set cmd = ($cmd --gm-gt-wm $Slope2);
 if($#surfcost)  set cmd = ($cmd --surf-cost $surfcost);
@@ -619,6 +622,15 @@ while( $#argv != 0 )
       set Interp = trilinear
       breaksw
 
+    case "--label":
+      if($#argv < 1) goto arg1err;
+      set MaskLabel = $argv[1]; shift;
+      if(! -e $MaskLabel) then
+        echo "ERROR: cannot find $MaskLabel"
+        exit 1;
+      endif
+      breaksw
+
     case "--epi-mask":
       set UseEPIMask = 1;
       breaksw
@@ -776,6 +788,8 @@ echo "   --proj-abs  dist : use wm and gm proj abs in 2nd stage"
 echo "   --subsamp nsub : 2nd stage vertex subsampling, default is 1"
 echo "   --nearest  : 2nd stage, use nearest neighbor interp (defalt is trilinear)"
 echo "   --epi-mask : mask out brain edge and B0 regions (1st and 2nd stages)"
+echo "   --no-cortex-label : do not mask by ?h.cortex.label"
+echo "   --label labelfile : mask by labelfile"
 echo "   --brute1max max     : pass 1 search -max to +max (default $Brute1Max)"
 echo "   --brute1delta delta : pass 1 search -max to +max step delta (default $Brute1Delta)" 
 echo "   --subsamp1 nsubsamp  : pass 1 vertex subsampling (default $nSubSamp)"
@@ -904,4 +918,6 @@ EXAMPLES:
      bbregister --s bert --mov partial.nii --init-fsl \
        --int whole.nii --reg register.partial.dat
      tkregister2 --mov partial.nii --reg register.partial.dat --surf
+
+
 
