allow specifying a gca file outside of the default freesurfer_home/average directory

diff --git a/scripts/recon-all b/scripts/recon-all
--- a/scripts/recon-all
+++ b/scripts/recon-all
@@ -8,8 +8,8 @@
 # Original Author: Doug Greve
 # CVS Revision Info:
 #    $Author: nicks $
-#    $Date: 2009/11/05 22:24:03 $
-#    $Revision: 1.133.2.59 $
+#    $Date: 2010/01/12 16:57:25 $
+#    $Revision: 1.133.2.60 $
 #
 # Copyright (C) 2002-2009,
 # The General Hospital Corporation (Boston, MA).
@@ -27,7 +27,7 @@
 #
 umask 002;
 
-set VERSION = '$Id: recon-all,v 1.133.2.59 2009/11/05 22:24:03 nicks Exp $';
+set VERSION = '$Id: recon-all,v 1.133.2.60 2010/01/12 16:57:25 nicks Exp $';
 set ProgName = `basename $0`;
 
 set inputargs = ($argv);
@@ -169,7 +169,7 @@ set robust_template_avg_arg = 1; # construct template from: 0 Mean, 1 Median
 set brain_template = talairach_mixed_with_skull.gca
 set face_template  = face.gca
 
-# For subcortical segmentation
+# For subcortical segmentation (override with -gca and -gca-skull)
 set GCA      = RB_all_2008-03-26.gca
 set GCASkull = RB_all_withskull_2008-03-26.gca
 
@@ -1215,7 +1215,12 @@ skullstrip:
       set xopts2 = `fsr-getxopts mri_em_register $XOptsFile`;
       set cmd2 = (mri_em_register)
       set cmd2 = ($cmd2 -skull)
-      set cmd2 = ($cmd2 $xopts2 nu.mgz $FREESURFER_HOME/average/$GCASkull)
+      set cmd2 = ($cmd2 $xopts2 nu.mgz)
+      if( -e $FREESURFER_HOME/average/$GCASkull) then
+        set cmd2 = ($cmd2 $FREESURFER_HOME/average/$GCASkull)
+      else
+        set cmd2 = ($cmd2 $GCASkull)
+      endif
       set cmd2 = ($cmd2 transforms/talairach_with_skull.lta)
       echo "\n $cmd2 \n"|& tee -a $LF |& tee -a $CF
       if($RunIt) $fs_time $cmd2 |& tee -a $LF
@@ -1225,8 +1230,13 @@ skullstrip:
 
     if ($WSGcaAtlas) then
       # if just using -brain_atlas flag, then include necessary options
-      set opts = (-brain_atlas $FREESURFER_HOME/average/$GCASkull \
-                  transforms/talairach_with_skull.lta $opts)
+      if( -e $FREESURFER_HOME/average/$GCASkull) then
+        set opts = (-brain_atlas $FREESURFER_HOME/average/$GCASkull \
+                    transforms/talairach_with_skull.lta $opts)
+      else
+        set opts = (-brain_atlas $GCASkull \
+                    transforms/talairach_with_skull.lta $opts)
+      endif
     endif
   endif
 
@@ -1305,7 +1315,11 @@ skullstrip:
         set BMA = brainmask_${vol}_PFH${pfh}.auto.mgz
         set LTA = transforms/talairach_with_skull.lta
         set cmd = (mri_log_likelihood -orig T1.mgz $BMA)
-        set cmd = ($cmd $xopts $FREESURFER_HOME/average/$GCA $LTA)
+        if( -e $FREESURFER_HOME/average/$GCA) then
+          set cmd = ($cmd $xopts $FREESURFER_HOME/average/$GCA $LTA)
+        else
+          set cmd = ($cmd $xopts $GCA $LTA)
+        endif
         echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
         if($RunIt) then
           $fs_time $cmd |& tee -a $LF |& tee -a ll_tmp
@@ -1419,13 +1433,22 @@ if($DoGCAReg) then
     if($DoCreateBaseSubj) then
       # base subj processing (norm_template instead of nu, and no mask needed):
       set cmd = (mri_em_register -mask brainmask.mgz $xopts \
-                  norm_template.mgz $FREESURFER_HOME/average/$GCA \
+                  norm_template.mgz)
+      if( -e $FREESURFER_HOME/average/$GCA) then
+        set cmd = ($cmd $FREESURFER_HOME/average/$GCA \
                   transforms/talairach.lta)
+      else
+        set cmd = ($cmd $GCA transforms/talairach.lta)
+      endif
     else
       # default processing:
-      set cmd = (mri_em_register -mask brainmask.mgz $xopts \
-                  nu.mgz $FREESURFER_HOME/average/$GCA \
+      set cmd = (mri_em_register -mask brainmask.mgz $xopts nu.mgz)
+      if( -e $FREESURFER_HOME/average/$GCA) then
+        set cmd = ($cmd $FREESURFER_HOME/average/$GCA \
                   transforms/talairach.lta)
+      else
+        set cmd = ($cmd $GCA transforms/talairach.lta)
+      endif
     endif
   endif
   echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
@@ -1472,7 +1495,11 @@ if($DoCANormalize) then
     # default stream
     set cmd = ($cmd nu.mgz)
   endif
-  set cmd = ($cmd $FREESURFER_HOME/average/$GCA)
+  if( -e $FREESURFER_HOME/average/$GCA) then
+    set cmd = ($cmd $FREESURFER_HOME/average/$GCA)
+  else
+    set cmd = ($cmd $GCA)
+  endif
   set cmd = ($cmd transforms/talairach.lta norm.mgz)
 
   echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
@@ -1505,9 +1532,14 @@ if($DoCAReg) then
   endif
   set cmd = ($cmd $UseCAAlignAfter)
   set cmd = ($cmd -mask brainmask.mgz)
-  set cmd = ($cmd $xopts norm.mgz \
-             $FREESURFER_HOME/average/$GCA \
+  set cmd = ($cmd $xopts norm.mgz)
+  if( -e $FREESURFER_HOME/average/$GCA) then
+    set cmd = ($cmd $FREESURFER_HOME/average/$GCA \
              transforms/talairach.m3z)
+  else
+    set cmd = ($cmd $GCA \
+             transforms/talairach.m3z)
+  endif
   echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
   if($RunIt) $fs_time $cmd |& tee -a $LF
   set st = $status
@@ -1550,8 +1582,12 @@ if($DoRemoveNeck) then
     set xform = (transforms/talairach.lta)
   endif
   set cmd = (mri_remove_neck -radius $RmNeckRadius $xopts \
-             nu.mgz $xform \
-             $FREESURFER_HOME/average/$GCA nu_noneck.mgz)
+             nu.mgz $xform)
+  if( -e $FREESURFER_HOME/average/$GCA) then
+    set cmd = ($cmd $FREESURFER_HOME/average/$GCA nu_noneck.mgz)
+  else
+    set cmd = ($cmd $GCA nu_noneck.mgz)
+  endif
   echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
   if($RunIt) $fs_time $cmd |& tee -a $LF
   if($status) goto error_exit;
@@ -1565,8 +1601,14 @@ if($DoSkullLTA) then
   cd $subjdir/mri > /dev/null
   set xopts = `fsr-getxopts mri_em_register $XOptsFile`;
   set cmd = (mri_em_register -skull -t transforms/talairach.lta \
-     $xopts nu_noneck.mgz $FREESURFER_HOME/average/$GCASkull \
+     $xopts nu_noneck.mgz)
+  if( -e $FREESURFER_HOME/average/$GCASkull) then
+    set cmd = ($cmd $FREESURFER_HOME/average/$GCASkull \
      transforms/talairach_with_skull.lta)
+  else
+    set cmd = ($cmd $GCASkull \
+     transforms/talairach_with_skull.lta)
+  endif
   echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
   if($RunIt) $fs_time $cmd |& tee -a $LF
   if($status) goto error_exit;
@@ -1667,7 +1709,11 @@ if($DoCALabel) then
   endif
   set cmd = ($cmd $xopts norm.mgz)
   set cmd = ($cmd transforms/talairach.m3z)
-  set cmd = ($cmd $FREESURFER_HOME/average/$GCA)
+  if( -e $FREESURFER_HOME/average/$GCA) then
+    set cmd = ($cmd $FREESURFER_HOME/average/$GCA)
+  else
+    set cmd = ($cmd $GCA)
+  endif
   set cmd = ($cmd ${asegbasename}.mgz)
   echo "\n $cmd \n"|& tee -a $LF |& tee -a $CF
   if($RunIt) $fs_time $cmd |& tee -a $LF
@@ -4341,14 +4387,17 @@ check_params:
   endif
 
   if(! -e $FREESURFER_HOME/average/$GCA ) then
-    echo "ERROR: cannot find $FREESURFER_HOME/average/$GCA" |& tee -a $LF
-    exit 1;
+    if(! -e $GCA ) then
+      echo "ERROR: cannot find $FREESURFER_HOME/average/$GCA or $GCA" |& tee -a $LF
+      exit 1;
+    endif
   endif
 
   if(! -e $FREESURFER_HOME/average/$GCASkull ) then
-    echo "ERROR: cannot find $FREESURFER_HOME/average/$GCASkull" \
-      |& tee -a $LF
-    exit 1;
+    if(! -e $GCASkull ) then
+      echo "ERROR: cannot find $FREESURFER_HOME/average/$GCASkull or $GCASkull" |& tee -a $LF
+      exit 1;
+    endif
   endif
 
   foreach hemi ($hemilist)
@@ -4896,7 +4945,7 @@ tkmedit and record the Volume Index values (NOT the XYZ coordinates).
 
 Specify the name of the gaussian classifier array (GCA) file
 to be used with GCA registration and automatic subcortical
-segmentation. It must be found in the FREESURFER_HOME/average directory.
+segmentation. 
 The Default is RB_all_YYYY-MM-DD.gca located in
 FREESURFER_HOME/average. This has no effect unless the GCA registration
 or subcortical segmentation stages are to be performed.
@@ -4904,7 +4953,7 @@ or subcortical segmentation stages are to be performed.
 -gca-skull gcafile
 
 Specify the name of the gaussian classifier array (GCA) file to be used with
-registration with skull.  It must be found in the FREESURFER_HOME/average
+registration with skull.
 directory. The default is RB_all_withskull_YYYY-MM-DD.gca located in
 FREESURFER_HOME/average.
 
